export const FETCH_CHARACTERS = "FETCH_CHARACTERS";
export const FETCH_CHARACTERS_START = "FETCH_CHARACTERS_START";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_FAIL = "FETCH_CHARACTERS_FAIL";

export const SEARCH_CHARACTERS = "SEARCH_CHARACTER";
export const SEARCH_CHARACTERS_START = "SEARCH_CHARACTERS_START";
export const SEARCH_CHARACTER_SUCCESS = "SEARCH_CHARACTER_SUCCESS";
export const SEARCH_CHARACTER_FAIL = "SEARCH_CHARACTER_FAIL";

export const DROPDOWN_CHANGE = "DROPDOWN_CHANGE";

export const EXTRACT_SPECIES = "EXTRACT_SPECIES";
export const EXTRACT_GENDERS = "EXTRACT_GENDERS";
export const EXTRACT_TYPES = "EXTRACT_TYPES";
export const EXTRACT_STATUS = "EXTRACT_STATUS";

export const APPLY_FILTERS = "APPLY_FILTERS";
export const APPLY_FILTERS_START = "APPLY_FILTERS_START";
export const APPLY_FILTERS_SUCCESS = "APPLY_FILTERS_SUCCESS";
export const APPLY_FILTERS_FAIL = "APPLY_FILTERS_FAIL";
